-- ledgerlift core schema. Portable across H2 (MODE=PostgreSQL) and PostgreSQL.

CREATE TABLE currencies (
    code        VARCHAR(3)   PRIMARY KEY,
    name        VARCHAR(64)  NOT NULL,
    precision_  SMALLINT     NOT NULL DEFAULT 2
);

CREATE TABLE ledgers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(64)  NOT NULL UNIQUE,
    currency_code VARCHAR(3)   NOT NULL REFERENCES currencies(code)
);

CREATE TABLE accounts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id    BIGINT       NOT NULL REFERENCES ledgers(id),
    code         VARCHAR(32)  NOT NULL,
    name         VARCHAR(128) NOT NULL,
    account_type VARCHAR(16)  NOT NULL, -- ASSET | LIABILITY | EQUITY | REVENUE | EXPENSE
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_accounts_ledger_code UNIQUE (ledger_id, code)
);

CREATE TABLE periods (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id  BIGINT      NOT NULL REFERENCES ledgers(id),
    name       VARCHAR(16) NOT NULL,            -- e.g. Mar-26
    start_date DATE        NOT NULL,
    end_date   DATE        NOT NULL,
    status     VARCHAR(8)  NOT NULL DEFAULT 'OPEN', -- OPEN | CLOSED
    CONSTRAINT uq_periods_ledger_name UNIQUE (ledger_id, name)
);

-- One row per uploaded file. Status machine:
--   LOADED -> VALIDATED -> POSTED
--          -> REJECTED (validation errors)
CREATE TABLE import_batches (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name  VARCHAR(255) NOT NULL,
    checksum     VARCHAR(64)  NOT NULL UNIQUE,   -- sha-256 of the uploaded bytes
    ledger_id    BIGINT       REFERENCES ledgers(id),
    status       VARCHAR(12)  NOT NULL DEFAULT 'LOADED',
    row_count    INTEGER      NOT NULL DEFAULT 0,
    parse_errors INTEGER      NOT NULL DEFAULT 0,
    error_count  INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    posted_at    TIMESTAMP
);

-- Staging / interface table: the FBDI template columns, as uploaded (strings
-- already typed where parsing succeeded; raw text kept for error correction).
CREATE TABLE gl_interface (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT        NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
    line_no          INTEGER       NOT NULL,   -- 1-based data line in the file
    ledger_name      VARCHAR(64),
    period_name      VARCHAR(16),
    journal_name     VARCHAR(128),
    line_description VARCHAR(255),
    account_code     VARCHAR(32),
    currency_code    VARCHAR(3),
    entered_dr       NUMERIC(20,2),
    entered_cr       NUMERIC(20,2),
    accounting_date  DATE,
    reference        VARCHAR(64),
    raw_line         VARCHAR(2000) NOT NULL,
    CONSTRAINT uq_gl_interface_batch_line UNIQUE (batch_id, line_no)
);

CREATE TABLE import_errors (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id     BIGINT       NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
    interface_id BIGINT       REFERENCES gl_interface(id) ON DELETE CASCADE,
    line_no      INTEGER,                        -- NULL for batch-level errors
    rule_code    VARCHAR(32)  NOT NULL,
    severity     VARCHAR(8)   NOT NULL,          -- ERROR | WARNING
    column_name  VARCHAR(32),
    message      VARCHAR(512) NOT NULL
);
CREATE INDEX ix_import_errors_batch ON import_errors(batch_id);

CREATE TABLE journal_headers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id      BIGINT        NOT NULL REFERENCES import_batches(id),
    ledger_id     BIGINT        NOT NULL REFERENCES ledgers(id),
    period_id     BIGINT        NOT NULL REFERENCES periods(id),
    journal_name  VARCHAR(128)  NOT NULL,
    currency_code VARCHAR(3)    NOT NULL REFERENCES currencies(code),
    total_dr      NUMERIC(20,2) NOT NULL,
    total_cr      NUMERIC(20,2) NOT NULL,
    posted_at     TIMESTAMP     NOT NULL,
    CONSTRAINT uq_journal_headers_batch_name UNIQUE (batch_id, journal_name)
);

CREATE TABLE journal_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    header_id       BIGINT        NOT NULL REFERENCES journal_headers(id),
    line_no         INTEGER       NOT NULL,
    account_id      BIGINT        NOT NULL REFERENCES accounts(id),
    entered_dr      NUMERIC(20,2) NOT NULL DEFAULT 0,
    entered_cr      NUMERIC(20,2) NOT NULL DEFAULT 0,
    accounting_date DATE          NOT NULL,
    description     VARCHAR(255),
    reference       VARCHAR(64),
    CONSTRAINT uq_journal_lines_header_line UNIQUE (header_id, line_no)
);
CREATE INDEX ix_journal_lines_account ON journal_lines(account_id);
